export enum Tables {
  User = 'users',
  FileUpload = 'file_uploads',
  Organization = 'organizations',
  OrganizationMember = 'organization_members',
  OrganizationRegistration = 'organization_registrations',
  CertificateType = 'certificate_types',
  Certificate = 'certificates',
  CertificateProfile = 'certificate_profiles',
  CertificateRequest = 'certificate_requests',
  Channel = 'channels',
  Post = 'posts',
  Comment = 'comments',
  Reaction = 'reactions',
  MediaFile = 'media_files',
}
